baseURL = "https://maxime.visonneau.fr/"
disqusShortname = "maxime-visonneau"
googleAnalytics = "UA-122087856-1"
languageCode = "en-US"
theme = "hucore"
tags = ["blog", "font awesome", "highlight.js"]
title = "Maxime VISONNEAU"

# [permalinks]
#   post = "/:year/:month/:day/:slug"

[params]
  author = "Maxime VISONNEAU"
  description = "Not fun stuff!"

[[params.social]]
url = "https://github.com/mvisonneau"
fa_icon = "fa-github"

[[params.social]]
url = "https://gitlab.com/mvisonneau"
fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/mvisonneau"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/mvisonneau"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

# [[menu.main]]
#   name = "Blog Posts"
#   weight = 100
#   identifier = "posts"
#   url = "/posts/"
#
# [[menu.main]]
#   name = "OS Projects"
#   identifier = "projects"
#   weight = 200
#   url = "/projects/"
